apiVersion: v1
kind: Service
metadata:
  name: hpa-deployment
spec:
  ports:
  - port: 80
    nodePort: 32000
    targetPort: http-port
    protocol: TCP
  selector:
    app: hpa-deployment
  type: LoadBalancer
